name: Validate deployment

description: 'Run end-to-end tests to validate the deployment.'

inputs:
  website-url:
    description: 'The URL of the website to test.'
    required: true
  test-title:
    description: 'The title of the test report.'
    required: true

runs:
  using: composite

  steps:
    - name: Install dependencies
      shell: bash
      working-directory: ./e2e
      run: |
        npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run e2e tests
      working-directory: ./e2e
      shell: bash
      run: |
        npx playwright test
      env:
        WEBSITE_URL: ${{ inputs.website-url }}
        TEST_TITLE: ${{ inputs.test-title }}